### ISSUE TITLE
ModuleNotFoundError: No module named 'cv2.cv2'

### ISSUE THREAD

**Issue by mfauvain** [pliablepixels/mlapi#23]
Recent system (Arch) upgrade (I guess mostly the python 3.8 -> 3.9 part) and mlapi is broken :
`Traceback (most recent call last):`
`  File "/home/x/.mlapi/mlapi.py", line 16, in <module>`
`    import cv2`
`  File "/usr/lib/python3.9/site-packages/cv2/__init__.py", line 3, in <module>`
`    from .cv2 import *`
`ModuleNotFoundError: No module named 'cv2.cv2'`

Tried to reinstall most of the python modules but cant figure out this one. I tried to install opencv2 but build fails.
Also tried to re-install mlapi from git clone, same error.
Any idea?

**Comment by mfauvain** [comment]
My error. reinstalled face_recognition python module and works now.
Closing.
